# Global settings applied to the whole site.
#
# [publish] is the directory to publish (relative to root of your repo),
# [command] is your build command,
# [base] is directory to change to before starting build. if you set base:
#    that is where we will look for package.json/.nvmrc/etc not repo root!

[build]
  base    = ""
  publish = "public/"
  command = "export NODE_OPTIONS=--max_old_space_size=8192 && gatsby build"
  [build.environment]
    WORDPRESS_HOST = "admin.tobiemarierrobitaille.com"
    WORDPRESS_USER = "admin"
    WORDPRESS_PASS = "zDjxF9kSZk@IntVG5xRH!YY@"
    PROTOCOL = "https"
    SITE_URL="https://tobiemarierrobitaille.com"


# # Specific branch context: Deploys from this branch
# # will take these settings and override their
# # current ones.
# [context.feature]
#   command = "make feature"

[[redirects]]
  from = "https://marierrobitaille.com"
  to = "https://tobiemarierrobitaille.com"
  status = 301

[[redirects]]
  from = "https://www.marierrobitaille.com"
  to = "https://tobiemarierrobitaille.com"
  status = 301

[[redirects]]
  from = "http://marierrobitaille.com"
  to = "https://tobiemarierrobitaille.com"
  status = 301

[[redirects]]
  from = "http://www.marierrobitaille.com"
  to = "https://tobiemarierrobitaille.com"
  status = 301

[[redirects]]
  from = "https://marierrobitaille.com/*"
  to = "https://tobiemarierrobitaille.com/:splat"
  status = 301

[[redirects]]
  from = "/admin"
  to = "https://admin.tobiemarierrobitaille.com/wp-admin/"
  status = 302

[[redirects]]
  from = "/fr/accueil/"
  to = "/fr/"
  status = 301

[[redirects]]
  from = "/en/home/"
  to = "/en/"
  status = 301

[[redirects]]
  from = "/fr/contact/"
  to = "/fr/a-propos/"
  status = 301

[[redirects]]
  from = "/en/contact-20/"
  to = "/en/about/"
  status = 301

[[redirects]]
  from = "/en/photos/"
  to = "/en/"
  status = 301

[[redirects]]
  from = "/fr/photos/"
  to = "/fr/"
  status = 301

[[redirects]]
  from = "/en/demo/"
  to = "/en/"
  status = 301

[[redirects]]
  from = "/fr/demo/"
  to = "/fr/"
  status = 301

[[redirects]]
  from = "/fr/movie/"
  to = "/fr/"
  status = 301

[[redirects]]
  from = "/1/photo/paysages.html"
  to = "/en/"
  status = 301

[[redirects]]
  from = "/fr/photo/paysages.html"
  to = "/fr/"
  status = 301

[[redirects]]
  from = "/en/photos/selected-work.html"
  to = "/en/"
  status = 301

[[redirects]]
  from = "/fr/movie/article/documentaire.html"
  to = "/fr/"
  status = 301

[[redirects]]
  from = "/fr/movie/article/fiction.html"
  to = "/fr/"
  status = 301